#!/bin/bash

MEDIACLIENT=/opt/bin/mediaclient
ENABLE_NETWORK=0
MOUNT_SUNDTEK=""

# rm avahi service files
rm -f /etc/avahi/services/sundtek*.service

[ -x "$MEDIACLIENT" ] || exit 0

[ -r /etc/default/sundtek ] && . /etc/default/sundtek

# enable network is done by sundtedtek.conf now

# scan for sundteks after staring driver
/usr/bin/scansundtek -v -w 30

# this will mount all sundtek devices which markt as staticly mounted in yavdr web frontend
initctl emit mount-sundtek

# try to mount devices
if [ -n "$MOUNT_SUNDTEK" ]; then
    for i in $MOUNT_SUNDTEK; do
        /opt/bin/mediaclient --mount=$i
    done
fi
